module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    extend: {
      zIndex: {
        '-10': '-10',
      },
      inset: {
        'mobile-skill-icon-top': '34px',
        'md-skill-icon-top': '28px',
        'xl-skill-icon-top': '16px',
        'xl-skill-icon-left': '32px',
      },
      borderRadius: {
        'card': '8px',
      },
      colors: {
        'custom-grey-100': '#E0E0E0 !important',
        'custom-grey-200': '#C0C0C0',
        'custom-grey-300': '#A0A0A0',
        'custom-grey-400': '#808080',
        'custom-grey-500': '#606060',
        'skill-card-header-blue': '#D4EBF2',
        'skill-card-header-red': '#FFB2B2',
        'skill-card-header-green': '#B2D8B2',
        'skill-card-header-purple': '#D8B2D8',
        'skill-card-header-yellow': '#FFFFB2',
        'header-blue': '#1FA2F2',
        'header-blue-grey': '#262D37',
        'background-blue-100': '#56667D',
        'background-blue-200': '#465365',
        'background-blue-300': '#36404E',
        'background-blue-400': '#161A20',
      },
      fontFamily: {
        'fira-mono': "Fira Mono",
        'roboto-mono': "Roboto Mono"
      },
      fontSize: {
        'h1': '36px',
        'h2': '28px',
        'h3': '24px',
        'h4': '20px',
        'h5': '18px',
        'h6': '16px',
        'p': '14px',
        'lg-header-title': '48px',
        'xl-header-title': '64px',
      },
      height: {
        'fit-content': 'fit-content',
        'skill-card-header': '64px',
      },
      margin: {
        '10px': '10px',
        '20px': '20px',
        '30px': '30px',
        '40px': '40px',
        '50px': '50px',
        '60px': '60px',
        '70px': '70px',
        '80px': '80px',
        '90px': '90px',
        '100px': '100px',
      },
      maxWidth: {
        'mobile-body': '300px',
        'md-body': '600px',
        'lg-body': '800px',
        'xl-body': '1280px',
      },
      padding: {
        '10px': '10px',
        '20px': '20px',
        '30px': '30px',
        '40px': '40px',
        '50px': '50px',
        '60px': '60px',
        '70px': '70px',
        '80px': '80px',
        '90px': '90px',
        '100px': '100px',
      },
      screens: {
        'xl': '1440px',
      },
      width: {
        'fit-content': 'fit-content',
        'mobile-skill-icon': '60px',
        'md-skill-icon': '72px',
        'xl-skill-icon': '96px',
        'mobile-skill-card': '300px',
        'md-skill-card': '240px',
        'lg-skill-card': '340px',
        'xl-skill-card': '370px',
        'mobile-body': '300px',
        'md-body': '600px',
        'lg-body': '800px',
        'xl-body': '1280px',
      },
    },
  },
  variants: {},
  plugins: [],
}
